### ISSUE TITLE
깃허브 쓰기 권한이 없습니다.

### ISSUE THREAD

**Issue by yeomyeom** [seonghapark/counterUAV#30]
일지 올리려고 하는데 퍼미션 디나이가 뜹니다.
삭제했다 클론해도 안되는거 보면 제 계정에 쓰기 권한이 없는것 같습니다.
yeomyeom(염승윤입니다.) 권한 다시 한번 확인 부탁드리겠습니다.

**Comment by seonghapark** [comment]
제가 보내드린 초대에 응하지 않았기 때문에 권한이 주어지지 않은 것입니다.
초대 확인해보세요.

<img width="751" alt="Screen Shot 2019-07-14 at 11 01 29 PM" src="https://user-images.githubusercontent.com/19395394/61195075-754a9d80-a68b-11e9-99c6-4ab891eb1f5e.png">
